<a href="https://colab.research.google.com/github/sskboonmee/multivariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#function
หน้าที่คือรับ input และทำตามกระบวนการละก็ได้ Output ออกมา


In [1]:
def function_name(_Input_) :
   do_something with _Input_ to produce _Output_
   return _Output_ 

SyntaxError: ignored

function ของ python มีส่วนสำคัญทั้งหมด 4 ส่วน 
1.บอก python ว่าเราจะเขียนฟังก์ชันอะไร def function_name(): ซึ่งขาดไม่ได้เป็นส่วนสำคัญ
2.กำหนดตัวแปรที่จะเป็น Input 
3.ส่วนประมวลผล do_something with input to get Output 
4.ส่วน output return Output 

ใช้เว้นวรรคบอกขอบเขตของฟังก์ชัน

####สร้างฟังก์ชัน

In [2]:
def print_name(name,surname,ID):
    st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
    return st
print('Outside  function')  #อันนี้คืออกจากฟังก์ชันเพราะมันไม่ได้อยู่ในฟังก์ชันขอบเขตก็คือที่วรรคเข้าไป

Outside  function


####เรียกใช้ฟังก์ชัน

In [3]:
output_string = print_name('ศศิกานต์' , 'บุญมี' , '623020539-9' )
print (output_string)

ชื่อ ศศิกานต์ นามสกุล บุญมี ID 623020539-9


####ฟังก์ชันไม่จำเป็นต้องมี Output

In [4]:
def print_name2(surname,ID,name):
    st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)

In [5]:
print_name2('ศศิกานต์' , 'บุญมี' , '623020539-9')

ชื่อ 623020539-9 นามสกุล ศศิกานต์ รหัส บุญมี


In [6]:
op2 = print_name2(' ศศิกานต์' , 'บุญมี' , '623020539-9' )

ชื่อ 623020539-9 นามสกุล  ศศิกานต์ รหัส บุญมี


In [7]:
print(op2)

None


####ฟังก์ชันไม่จำเป็นต้องมี Input

In [8]:
def Pi():   #อันนี้แค่แบบreturnค่าที่เราต้องการเฉยๆ
    return 3.14159265359

In [9]:
#คำนวณพื้นที่วงกลมที่มีขนาดเส้นผ่าศูนย์กลางเท่ากับ 3 
Pi()*(1.5**2)

7.0685834705775

In [10]:
def print_my_name():
    print('ศศิกานต์  บุญมี  ID6230205399')

In [11]:
print_my_name()

ศศิกานต์  บุญมี  ID6230205399


### 1.input ของ Function ใน Python มี 2 แบบ  คือแบบที่จำเป็นต้องใส่กับไม่จำเป็นต้องใส่ 
(มีค่า Default) เราต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน

####2.เราต้องเรียง Input ที่จำเป็นขึ้นก่อน

In [12]:
def print_2lines_default(name, surname, ID, grade='F'):
    st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)
    st2=f'เกรดวิชา Multivariate >>> {grade}'
    print(st2)

In [13]:
print_2lines_default('ศศิกานต์' , 'บุญมี' , '623020539-9')

ชื่อ ศศิกานต์ นามสกุล บุญมี รหัส 623020539-9
เกรดวิชา Multivariate >>> F


In [14]:
print_2lines_default('ศศิกานต์' , 'บุญมี' , '623020539-9' ,'A')

ชื่อ ศศิกานต์ นามสกุล บุญมี รหัส 623020539-9
เกรดวิชา Multivariate >>> A


####เราสามารถเรียกฟังก์ชันโดยใช้ชื่อตัวแปรของฟังก์ชันช่วยได้

In [15]:
print_name2(name='ศศิกานต์' , surname='บุญมี' , ID='623020539-9')

ชื่อ ศศิกานต์ นามสกุล บุญมี รหัส 623020539-9


###HW ให้เขียน function คำนวณจำนวนวินาทีจาก เวลา ต่อไปนี้

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

และ print ให้สวยงาม

In [16]:
def function_q (times):
    q = f'เวลาทั้งหมด = {times}'
    print(q)
    times_sp = times.split('-')
    h = int(times_sp[0])*3600
    m = int(times_sp[1])*60
    s = int(times_sp[2])
    aq = h+m+s
    print(f'คำนวณเป็นวินาทีได้เท่ากับ {aq} วินาที')
   



In [17]:
function_q('14-15-31')

เวลาทั้งหมด = 14-15-31
คำนวณเป็นวินาทีได้เท่ากับ 51331 วินาที


In [18]:
function_q('13-00-01')

เวลาทั้งหมด = 13-00-01
คำนวณเป็นวินาทีได้เท่ากับ 46801 วินาที


In [19]:
function_q('05-49-44')

เวลาทั้งหมด = 05-49-44
คำนวณเป็นวินาทีได้เท่ากับ 20984 วินาที


In [20]:
function_q('00-00-16')

เวลาทั้งหมด = 00-00-16
คำนวณเป็นวินาทีได้เท่ากับ 16 วินาที


##Numpy  -> package สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

Num+py ->Number-Numerical + python 

การใช้ package
1.import ชื่อ package #เรียกใช้ Package 
2.ชื่อ package.ชื่อฟังก์ชัน #เรียกใช้function

In [21]:
import numpy

data structure -> array 

In [23]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


ชื่อค่าใน numpy array

In [24]:
mat_ex1[1,1]  #[แถว,หลัก]  #แถวแนวนอนหลักแนวตั้ง

0.1

ถ้าไม่มี numpy array

In [26]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [ ]:
list_ex1[1,1]

In [27]:
list_ex1[1][1]

0.1

In [28]:
print(list_ex1)
a = list_ex1[1]
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


##Matrix Operations
data -> 2 แบบ matrix(2D array ) , scalar (ตัวเลขค่าคงที่)

In [29]:
mat_ax1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2 = numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


##บวกกับลบ matrix เอาตัวเลขตำแหน่งเดียวกันมาบวกหรือลบกัน 
(หน้าตาของ matrix ต้องเหมือนกัน)

In [33]:
mat_ex0 = numpy.array ([[1,2],[3,4]])
print(mat_ex0)

[[1 2]
 [3 4]]


In [30]:
mat_ex3 = mat_ex1 + mat_ex2
print(mat_ex3)
mat_ex4 = mat_ex1 - mat_ex2
print(mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


In [ ]:
mat_ex1 + mat_ex0 

การตรวจสอบขนาดของ matrix  ใช้คำว่า shape

In [34]:
mat_ex3.shape

(2, 3)

In [35]:
mat_ex3.shape[0]

2

##คูณ matrix

In [36]:
print(mat_ex1)
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


In [38]:
mat_ex1 * mat_ex2  #incorrect

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

## การคูณ matrix (แถวคูณหลัก)
(หลักของตัวข้างหน้าต้องเท่ากับแถวของตัวข้างหลัง)


dot product  ( (AAA,x),(x,ZZZ) ) = (AAA,ZZZ)

In [39]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


# Transpose กลับแถวเป็นหลักกลีบหลักเป็นแถว

matrix.T

In [45]:
numpy.dot(mat_ex1,mat_ex2.T)  #(2,3.(3,2))

array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

In [47]:
numpy.dot(mat_ex1.T,mat_ex2) #(3,2).(2,3) = (3,3)

array([[838.5 ,  32.89,  97.11],
       [ 15.1 ,  11.25,  18.43],
       [ 36.3 ,  17.1 ,  28.74]])

HW 4 อธิบายการหา Deteminant และ Inverse matrix (รูปและคำอธิบาย)