<a href="https://colab.research.google.com/github/sskboonmee/multivariate/blob/main/Multivariate_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ให้นักศึกษาทำข้อสอบใน Colab Notebook นี้โดยกรอกข้อมูลของตัวเองใน cell ที่ 2 แล้วรัน cell ที่ 1 - 5 และเริ่มทำข้อสอบใน cell ที่ 6 เป็นต้นไป

โดยโจทย์คือ
1. ข้อมูลโจทย์ อยู่ใน ตัวแปร ```Data```
2. ทำ clustering แล้วทำ visualize ข้อมูลแบบ 2 มิติ
3. ลด Dimension ของข้อมูลเหลือ 2 มิติ แล้วทำ clustering แล้ว visualize ข้อมูลแบบ 2 มิติ
4. เปรียบเทียบความแตกต่างของผลข้อ 2. กับ ข้อ 3.
5. เขียน comments อธิบายทุกขั้นตอน
6. อัด video อธิบาย code ทุกๆขั้นตอนรวมถึงผลแล้วอัพลง youtube ในรูปแบบ unlist 
7. commit โดยใช้ชื่อ commit เป็น link youtube ที่อธิบาย code ในข้อ 6.

กำหนดส่งวันที่ 2 พฤษภาคม 2564 (โดยให้มากรอกวันที่ commit ครั้งสุดท้ายใน sheet: https://docs.google.com/spreadsheets/d/1_qJwLDJVtOW1HxBcf_FHVc6UT4J_SOonuR6o3EEnVzw/edit?usp=sharing ช่อง Final)

In [1]:
from sklearn.datasets import make_blobs
import random,math
import numpy as np
import pandas

In [2]:
Name = 'ศศิกานต์ บุญมี'
ID = '6230205399'

In [3]:
def DataGenerator(name,id):
    random.seed(int(id[3:6]))
    numfeat = random.randint(20,30)
    ct = random.randint(len(name)-6,len(name))
    
    X, y = make_blobs(n_samples=10000, centers=ct, n_features=numfeat , random_state=int(id[3:6]))

    print(f'{id[3:6]}:{numfeat}:{ct}')
    X_t = (X[:,1]*2)+int(id[3])
    X_t2 = (X[:,-1]*5)+int(id[4])

    DT = np.append(X,X_t.reshape([10000,1]),axis=1)
    DT = np.append(DT,X_t2.reshape([10000,1]),axis=1)
    
    return pandas.DataFrame(DT)

In [4]:
Data = DataGenerator(Name,ID)

020:30:14


In [5]:
Data

0          1          2   ...        29         30         31
0     5.779841   9.590162   7.580040  ...  2.942146  19.180325  16.710729
1    -1.969309  -5.779929  -0.479035  ...  7.465699 -11.559858  39.328496
2     3.599102   3.524340  -6.054480  ...  2.749403   7.048680  15.747013
3     2.610732   2.268904  -4.365511  ...  0.589666   4.537807   4.948332
4     1.229763   6.218683   6.069170  ...  7.252844  12.437365  38.264218
...        ...        ...        ...  ...       ...        ...        ...
9995  4.115431   7.000837  -9.653089  ...  3.938198  14.001675  21.690991
9996  8.642016 -10.310443  -4.164195  ...  4.496800 -20.620886  24.484000
9997  2.576362  -2.282850  -1.977706  ...  1.419396  -4.565701   9.096982
9998  5.623216   6.132319  -9.526871  ...  4.450119  12.264638  24.250595
9999  4.645371   6.691490 -10.926293  ...  5.503867  13.382980  29.519334

[10000 rows x 32 columns]

##Kmean
มี 3 ขั้นตอน คือ import Define Fit-tranform

####import

In [6]:
from sklearn.cluster import KMeans  

####Define

เป็นการกำหนดว่าKmeans มีตัวอะไรให้กำหนดบ้าง random state เป็นการกำหนดให้ได้ผลลัพธ์เหมือนกัน เนื่องจาก Kmeans เวลาสุ่มจะสุ่มจากเลขตัวไหนก็ได้ เราเลยต้อง fix ให้มันสุ่มจากเลขเดียวกัน ก็จะได้เหมือนๆกัน n_cluster คือการเซตค่า K

In [103]:
kmeans = KMeans(n_clusters=4, random_state=0)  

####Fit-tranform

คำนวณจุด Cluster center ของข้อมูล Data ด้วยวิธี K-means clustering

In [104]:
kmeans.fit(Data)  #fit คือเอามาคำนวณว่าจุด Cluster center จะเป็นจุดไหน

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=4, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=0, tol=0.0001, verbose=0)

แสดงจุด Cluster center ที่คำนวณออกมาได้

In [97]:
kmeans.cluster_centers_

array([[-3.38017111e+00,  3.24596705e-02, -9.67409376e-01,
        -3.38344615e+00,  1.91951465e+00, -5.97600881e-01,
        -4.33991615e+00, -6.00650318e+00, -3.35027995e+00,
         1.53340996e+00, -7.82692160e-01,  2.70869277e+00,
         3.66270028e+00,  3.71141739e+00, -2.01429512e+00,
         3.13138132e+00,  4.33302343e+00,  3.49416316e+00,
        -7.60129625e+00,  1.66229417e+00,  1.24487275e+00,
         9.66181539e-01, -1.26493491e+00, -1.32773248e+00,
         1.07385162e+00, -5.86262675e+00,  1.50941704e+00,
        -2.07414652e-01,  2.27705049e+00, -8.00184449e+00,
         6.49193409e-02, -3.80092225e+01],
       [ 1.67582437e+00,  4.14120691e-01, -1.51258022e+00,
         2.57556363e+00,  2.47837774e-01,  1.17523367e+00,
         3.43230745e+00,  6.46757292e-01,  1.45854247e+00,
        -2.21587166e+00,  1.36047188e+00, -4.41632538e-01,
        -3.26466903e-01,  2.91065971e-01, -3.20745510e-01,
         4.00732310e-01, -1.54540220e-01,  2.23021869e+00,
         2.80

ทดสอบการจัดกลุ่มของ Data 

In [99]:
y = kmeans.predict(Data)
y

array([1, 1, 1, ..., 1, 1, 1], dtype=int32)

In [98]:
y = kmeans.predict(Data)
y

array([1, 1, 1, ..., 1, 1, 1], dtype=int32)

#### PCA

In [100]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)

new_pca = pca.fit_transform(Data)

In [101]:
from matplotlib import pyplot as plt

In [102]:
plt.plot(Data[2:,0],Data[2:,1],'or')
plt.plot(Data[1:2,0],Data[1:2,1],'og')
plt.plot(Data[2:,0],Data[2:,1],'oy')

KeyError: ignored

In [26]:
kmeans = KMeans(n_clusters=2, random_state=2021)
kmeans.fit(Data)
y = kmeans.predict(Data)
plt.scatter(Data[:,0],Data[:,1],c=y)

KeyError: ignored